### ISSUE TITLE
bgpstream setup which works locally fails in container

### ISSUE THREAD

**Issue by tomgreenwood1** [CAIDA/pybgpstream#30]
I have this code which works fine locally:

```python
    stream = pybgpstream.BGPStream(data_interface = "singlefile")
    stream.set_data_interface_option("singlefile", "upd-file", file_path)

    for elem in stream:
         print(str(elem))
```

When I run this exact same code in a container on kubernetes it fails silently. Everything up until iteration on the stream runs (there's some code above that in reality, and I put in some logging), but when it comes to the for-loop on the stream the process just stalls. No error message, just silence. 

I can exec into the container and check the file is there, and it is.

Any idea what's might be causing that?

Thanks

**Comment by alistairking** [comment]
Interesting!

It's especially odd that you're not getting any error messages.

Does the container work if you run it without putting it into k8s?

**Comment by tomgreenwood1** [comment]
Just tried that now. Exactly the same in local docker. Similarly, I can exec into the container and the file is there. I am using the caida/bgpstream:2.0.0-rc3 image as my base for the container, and I have other containers collecting from routeviews with this container, so it's something related to the singlefile...

**Comment by alistairking** [comment]
We'll try and reproduce the problem and see if we can figure this out

**Comment by tomgreenwood1** [comment]
Thanks very much

**Comment by digizeph** [comment]
Hi @tomgreenwood1, we have updated the bgpstream docker images with a fix that should resolve your issue. Could you try use `caida/bgpstream:2.0.0-rc4` image as base, rebuild your image with `--no-cache` option, and see if the issue is resolved? Thanks!

**Comment by tomgreenwood1** [comment]
Hi @digizeph I can confirm that has resolved the issue. Thanks.
