### ISSUE TITLE
Allow time to be given as float

### ISSUE THREAD

**Issue by alistairking** [CAIDA/pybgpstream#40]
Currently the datetime parsing code at https://github.com/CAIDA/pybgpstream/blob/e837264bd7481ff813acd3ac75cf5b123272479f/pybgpstream/pybgpstream.py#L101-L110
triggers an assertion if the given time is a float (as is the case when passing `time.time()`).

**Comment by digizeph** [comment]
@alistairking I added the support for floating number timestamps in PR #41, could you take a look?

**Comment by brendonj** [comment]
#41 has been merged.
