### ISSUE TITLE
prefix filter does not work

### ISSUE THREAD

**Issue by PolynomialDivision** [CAIDA/pybgpstream#8]
If I try to add

    stream.add_filter('prefix-exact', '13.52.0.0/14')

it does not work. It gives me other prefixes too ``13.54.0.0/15``...

**Comment by alistairking** [comment]
My apologies for not seeing this issue!
This problem should be fixed since the bgpstream 1.2.0 release. Can you please try using the latest libbgpstream version (i.e., you'll need to upgrade both libbgpstream and pybgpstream) and see if you still see incorrect prefixes?
